### PR TITLE
statsmodels compatibility

### LINKED ISSUE #10: Cox regression broke with latest StatsModels master
Not sure what's happening (unfortunately I don't remember any more what manipulations StatsModels does to `fit` before calling `fit` with arrays):

```julia
julia> using Survival, DataFrames, StatsModels

julia> df = DataFrame(x = rand(4), y = EventTime.(rand(4), rand(Bool, 4)))
4×2 DataFrame
│ Row │ x        │ y         │
│     │ Float64  │ EventTim… │
├─────┼──────────┼───────────┤
│ 1   │ 0.827601 │ 0.662955+ │
│ 2   │ 0.909557 │ 0.0749414 │
│ 3   │ 0.379872 │ 0.0578822 │
│ 4   │ 0.122107 │ 0.712976  │

julia> fit(CoxModel, @formula(y ~ x), df)
ERROR: MethodError: no method matching fit(::Type{CoxModel}, ::Array{Float64,2}, ::Array{Float64,2})
Closest candidates are:
  fit(::Type{Histogram}, ::Any...; kwargs...) at /home/pietro/.julia/dev/StatsBase/src/hist.jl:319
  fit(::StatisticalModel, ::Any...) at /home/pietro/.julia/dev/StatsBase/src/statmodels.jl:151
  fit(::Type{T<:RegressionModel}, ::FormulaTerm, ::Any, ::Any...; contrasts, kwargs...) where T<:RegressionModel at /home/pietro/.julia/dev/StatsModels/src/statsmodel.jl:82
  ...
Stacktrace:
 [1] #fit#57(::Dict{Symbol,Any}, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{,Tuple{}}}, ::Function, ::Type{CoxModel}, ::FormulaTerm{Term,Term}, ::DataFrame) at /home/pietro/.julia/dev/StatsModels/src/statsmodel.jl:88
 [2] fit(::Type{CoxModel}, ::FormulaTerm{Term,Term}, ::DataFrame) at /home/pietro/.julia/dev/StatsModels/src/statsmodel.jl:82
 [3] top-level scope at none:0
```

### PR DESCRIPTION
**Pull request by kleinschmidt**
treat vectors of EventTimes like continuous terms.  needs JuliaStats/StatsModels.jl#106 (to just copy continuous terms instead of converting to Float64).

fixes #10 , #16

### CODE REVIEW

File: src/eventtimes.jl [hunk 1]
```diff
@@ -39,3 +39,9 @@ end
 
 isevent(ev::EventTime) = ev.status
 iscensored(ev::EventTime) = !ev.status
+
+## StatsModels compatibility
+
+StatsModels.concrete_term(t::Term, xs::AbstractVector{<:EventTime}, ::Nothing) =
+    StatsModels.ContinuousTerm(t.sym, first(xs), first(xs), first(xs), first(xs))
+Base.copy(et::EventTime) = et
```
Comment (ararslan) [inline src/eventtimes.jl]: Shouldn't this actually copy? Like `EventTime(copy(et.time), copy(et.status))`

Comment (ararslan) [reply src/eventtimes.jl]: I guess that's a no-op though since numbers and `Bool`s are immutable. Though I guess the time could be a `BigFloat`, for which `copy` actually does something (I think?).

Comment (kleinschmidt) [reply src/eventtimes.jl]: I dunno I was lazy

Comment (kleinschmidt) [reply src/eventtimes.jl]: It's immutable though right?

Comment (kleinschmidt) [reply src/eventtimes.jl]: I mean it is up 2 u

Comment (ararslan) [reply src/eventtimes.jl]: Nah, this is fine.

**Comment by ararslan** [comment]
You'll probably want to turn the StatsModels upper bound in the Project.toml into a lower bound in order for this to work, since `concrete_term` isn't defined without Son of Terms.

**Comment by ararslan** [comment]
I guess we'll need to wait until StatsModels is tagged, since otherwise the StatsModels version requirement is unsatisfiable.

File: src/eventtimes.jl [hunk 2]
```diff
@@ -39,3 +39,9 @@ end
 
 isevent(ev::EventTime) = ev.status
 iscensored(ev::EventTime) = !ev.status
+
+## StatsModels compatibility
+
+StatsModels.concrete_term(t::Term, xs::AbstractVector{<:EventTime}, ::Nothing) =
+    StatsModels.ContinuousTerm(t.sym, first(xs), first(xs), first(xs), first(xs))
```
Comment (nalimilan) [inline src/eventtimes.jl]: Why not actually compute the mean, variance, min and max?

Comment (kleinschmidt) [reply src/eventtimes.jl]: Is that even defined for event times?  How would the truncation be handled?

Maybe a better option is to add methods like `mean(<:AbstractVector{<:EventTime})`?

Comment (nalimilan) [reply src/eventtimes.jl]: Hard to tell... But it also sounds weird to pass identical values. Maybe `nothing` should be allowed?

**Comment by kleinschmidt** [comment]
Tests pass locally for me with StatsModels 0.6.0 but I've restarted the travis job to make sure...

**Comment by ararslan** [comment]
Has the StatsModels 0.6.0 tag not been merged or something?

**Comment by kleinschmidt** [comment]
No it has but it lists julia >= 1 in the project.toml so that 0.7 build failed...do you care about 0.7 compatibility still?

**Comment by kleinschmidt** [comment]
(I'll update the travis config and Project.toml in this PR if you want to drop 0.7 support...)

**Comment by ararslan** [comment]
Down with 0.7! Down with 0.7!

**Comment by ararslan** [comment]
Oh, I see, I was fooled because I was looking at the push build rather than the PR build. That's why I didn't see that it was only not working on 0.7.

**Comment by kleinschmidt** [comment]
I guess also the version should be bumped right?

**Comment by ararslan** [comment]
Yep

File: src/eventtimes.jl (hunk 1 above)
Comment (ararslan) [inline src/eventtimes.jl]: Is this actually necessary? Coverage says this line isn't covered which means it isn't being used by anything. (Anything that's currently tested, anyway.)

Comment (kleinschmidt) [reply src/eventtimes.jl]: huh, it should be hit by https://github.com/JuliaStats/StatsModels.jl/blob/master/src/terms.jl#L475

I'll look into it...

Comment (kleinschmidt) [reply src/eventtimes.jl]: Maybe it gets compiled away?  I was going to say it's probably because `EventTime` is immutable but I'm not sure.  When that line is removed there's an error because `modelcols` calls `copy.(table[term.sym])`

Comment (ararslan) [reply src/eventtimes.jl]: Huh, weird.
